DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'pwd/', include('password.urls', namespace='password')),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', DjangoBlogFeed()),
    url(r'^rss/$', DjangoBlogFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
]
urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

apps/password/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.http import HttpResponse
from django.urls import path

from password.views import PwdView

app_name = "pwd"

urlpatterns = [
    path(r'', PwdView.as_view(), name='enter'),

]

templates/pwd/enter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>输入密码</title>
    <style>
        div {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .password {
            width: 300px;
            height: 50px;
        }

        .submit {
            width: 50px;
            height: 30px;
            margin: 0 auto;
        }
        span {
            width: 50px;
            height: 30px;
            margin: 0 auto;
        }

    </style>
</head>
<body>
<div>
    <form action="{% url "pwd:enter" %}" method="post">
        {% csrf_token %}
        <input class="password" type="password" name="password" placeholder="输入登录密码">
        {% if not check_result %}
            <span id="pwdErr" style="color: red">密码错误</span>
        {% endif %}
        <input class="submit" type="submit" style="display: block" value="进入">
    </form>
</div>
<a href="/" rel="nofollow">首页</a>

</body>
</html>
<script>
    setTimeout(function () {
        document.getElementById("pwdErr").remove()
    }, 2000)
</script>

templates/pwd/pwd_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>密码列表</title>
    <style>
        .list {
            margin: 0 auto;
        }

        .list > .row {
            margin-bottom: 10px;
        }

        .list > .row li {
            margin-right: 10px;
            width: 200px;
            text-align: center;
            word-break: break-word;
        }

        body, html {
            margin: 0;
            padding: 0;
        }

    </style>
</head>
<body>
<a href="/" rel="nofollow">首页</a>
<ul class="list" style="list-style: none">
    <li class="row">
        <ul style="display: flex;list-style: none">
            <li>账号</li>
            <li>密码</li>
            <li>描述</li>
            <li>链接</li>
        </ul>
    </li>
    {% for pwd_obj in pwds %}
        <li class="row">
            <ul style="display: flex;list-style: none">
                <li>{{ pwd_obj.username }}</li>
                <li>{{ pwd_obj.pwd }}</li>
                <li>{{ pwd_obj.desc }}</li>
                <li><a href="{{ pwd_obj.link }}" target="_blank">{{ pwd_obj.link }}</a></li>
            </ul>
        </li>
    {% endfor %}

</ul>

</body>
</html>